### PR TITLE
CODEOWNERS automation

### PR DESCRIPTION
**Pull request by erichs**
This script implements a mechanism to create CODEOWNERS files for all repos based on commit history and team membership.

It will ensure that teams specified in CODEOWNERS files are added with push/write access to the repository (which is a requirement for CODEOWNERS validation).

### CODE REVIEW

**Review by electricgull — DISMISSED** [review]

**Review by kenanwarren — DISMISSED** [review]
LGTM, one question does OctoKit take care of following the Github rate limiting headers?

**Comment by erichs** [comment]
@kenanwarren Not out of the box, but there is [a throttling plugin](https://github.com/octokit/plugin-throttling.js). I suspect we'll be OK with normal rate limits, since the loop isn't very tight (clone each repo sequentially), but this plugin should be a cinch to add, so I'll do so. The real trick, I think, is trying to stay below secondary rate limits, which don't appear as easy to recover from.

**Review by kenanwarren — DISMISSED** [review]
One thing of note with codeowners and how a lot of our Github repos are setup is you need to add the repositories to your Github team. The problem is to add the repos (it seems) you need to be an admin on that particular repo. Most of our CI/CD repos are before my time and so I'm not admin, not sure if this is specific to the SRE team or something others will run into. I can open a ticket for our particular repo to get admin rights, but just an FYI if other teams run into similar issues.
Screen Shot 2022-03-16 at 5 57 48 PM

**Comment by erichs** [comment]
^^ this is being automatically handled here: https://github.com/JupiterOne/secops-automation-examples/pull/68/files#diff-acfcc48b6c2bcebe9a65ac45751904269bbd1761fa40c0717ea6bb331c4b70b5R32

**Review by electricgull — DISMISSED** [review]

**Review by electricgull — APPROVED** [review]

**Pull request merged**
